ifndef::imagesdir[:imagesdir: images]

=== Application Context API

Rico provides an application context that can be used to hold attributes in a global and a per-thread context.
An attribute is defined as a key-value pair.
Both key and values are strings.
These pairs can be stored and read from the global context or the context of the current thread only.
All attributes describe metadata to help in debugging, maintaining and analysing an application.

The interface `dev.rico.core.context.RicoApplicationContext` defines the application context in Rico and provides several methods to store and receive context based information.
Depending on your environment Rico provides different ways to obtain a `RicoApplicationContext` instance.

The following sample shows how values can be stored:

[source,java]
----

final RicoApplicationContext ricoContext = ... // <1>

ricoContext.setGlobalAttribute("application.type", "microservice"); // <2>
ricoContext.setThreadLocalAttribute("thread.type", "background thread"); // <3>
----
<1> depends on your environment.
<2> here an attribute is stored in the global context.
"application.type" is the name / key of the attribute and "microservice" is the value
<3> here an attribute is stored in the context of the current thread.

When storing thread based context information you normally want to keep the information for a specific task only and the information will be invalid afterwards.
To do so the following pattern is quite helpful when defining attributes in the thread context:

[source,java]
----

public final Result callDatabase(final String query) {
    final RicoApplicationContext ricoContext = ... // <1>
    final Assignment queryAttributeAssignment = ricoContext.setThreadLocalAttribute("db.query", query); // <2>

    try {
        return db.call(query); // <3>
    } finally {
        queryAttributeAssignment.unset(); // <4>
    }
}

----
<1> depends on your environment.
<2> here the attribute "db.query" is stored in the thread context.
The `Assignment` instance can be used to remove the added attribute from the context.
<3> While we call our database the context attribute "db.query" will remain set.
<4> Once the database call has been executed we remove the attribute from the thread context by calling the `unset()` method.
This should always be done in a `finally` block since an exception my prevent this otherwise.

==== Benefits of the application context

The application context in Rico is integrated in several libraries and features of Rico.
The remoting library of Rico automatically adds information to the context that can be helpful.
The metrics and logging libraries of Rico provide the possibility to enrich metrics and logging with context based attributes through the application context.
This allows you to easily assign all logging messages of a server to specific users and requests or to store the metrics of several microservices in the same Prometheus instance and query for a specific instance later.
More information can be found in the documentation of the metrics and logging API.

image:context-in-log.svg[]

==== Using the API on the client

In the Rico client API a `dev.rico.core.context.RicoApplicationContext` instance can be obtained by using by the following call:

[source,java]
----

final RicoApplicationContext ricoContext = Client.getService(RicoApplicationContext.class);
----

==== Using the API on the server

On JakartaEE and Spring you can inject a `dev.rico.core.context.RicoApplicationContext` instance in any managed bean.
The instance is always defined in the singleton / application scope.

==== Predefined Context values

Rico already defines some context attributes by default.
The following table gives an overview of all the context attributes that are defined by default when using Rico.

.Predefined context attributes
[cols="3,^2,^2,^4,10",options="header"]
|===
|attribute name |type |availability |sample |description

|application.name
|global
|always
|myApplication
|The name of the application if defined in the configuration by the "application.name" property. Otherwise "UNKNOWN"

|rico.version
|global
|always
|1.1.0
|The used version of Rico

|system.os
|global
|always
|mac
|Name of the used operation system. "linux", "mac", "win" or "unknown"

|java.version
|global
|always
|11.0.3
|The version of the used Java runtime

|java.vendor
|global
|always
|AdoptOpenJDK
|The vendor of the used Java runtime

|system.hostName
|global
|always
|my-macbook.karakun
|The host name of the system

|system.canonicalHostName
|global
|always
|my-macbook.karakun
|The canonical host name of the system

|system.hostAddress
|global
|always
|192.168.178.23
|The host address of the system

|thread
|thread
|always
|background-thread-2
|Name of the current thread. This is only supported for threads that are created by Rico

|uiToolkit
|global
|client
|JavaFX toolkit
|The name of the used UI toolkit. This value is only defined when using the rico-client library.

|security.userName
|global
|client
|admin
|When using rico-security this value defines the name of the logged in user on the client

|security.userName
|thread
|server
|admin
|When using rico-security this value defines the name of the logged in user for the current request on the server

|remoting.controller
|thread
|server
|WorkflowController
|Name of the remoting controller when a controller action is executed on the server.

|remoting.action
|thread
|server
|saveUser
|Name of the remoting controller action that is executed on the server.

|http.session
|thread
|server
|1342424
|id of the http session on the server

|http.clientSession
|thread
|server
|749516
|id of the http client session on the server
|===
