package dev.rico.integrationtests.remoting.value;

public interface ValueTestConstants {

    String BIG_DECIMAL_VALUE = "BIG_DECIMAL_VALUE";

    String BIG_INTEGER_VALUE = "BIG_INTEGER_VALUE";

    String PRIMITIVE_BOOLEAN_VALUE = "PRIMITIVE_BOOLEAN_VALUE";

    String BOOLEAN_VALUE = "BOOLEAN_VALUE";

    String PRIMITIVE_BYTE_VALUE = "PRIMITIVE_BYTE_VALUE";

    String BYTE_VALUE = "BYTE_VALUE";

    String PRIMITIVE_CHARACTER_VALUE = "PRIMITIVE_CHARACTER_VALUE";

    String CHARACTER_VALUE = "CHARACTER_VALUE";

    String PRIMITIVE_DOUBLE_VALUE = "PRIMITIVE_DOUBLE_VALUE";

    String DOUBLE_VALUE = "DOUBLE_VALUE";

    String PRIMITIVE_FLOAT_VALUE = "PRIMITIVE_FLOAT_VALUE";

    String FLOAT_VALUE = "FLOAT_VALUE";

    String PRIMITIVE_INTEGER_VALUE = "PRIMITIVE_INTEGER_VALUE";

    String INTEGER_VALUE = "INTEGER_VALUE";

    String PRIMITIVE_LONG_VALUE = "PRIMITIVE_LONG_VALUE";

    String LONG_VALUE = "LONG_VALUE";

    String PRIMITIVE_SHORT_VALUE = "PRIMITIVE_SHORT_VALUE";

    String SHORT_VALUE = "SHORT_VALUE";

    String STRING_VALUE = "STRING_VALUE";

    String ALL_VALUE_TYPES_CONTROLLER = "ALL_VALUE_TYPES_CONTROLLER";

    String OPTIONAL_VALUE_TYPES_CONTROLLER = "OPTIONAL_VALUE_TYPES_CONTROLLER";

    String NON_OPTIONAL_VALUE_TYPES_CONTROLLER = "NON_OPTIONAL_VALUE_TYPES_CONTROLLER";

    String BY_FIELD_NAME_DEFINED_VALUE_TYPES_CONTROLLER = "BY_FIELD_NAME_DEFINED_VALUE_TYPES_CONTROLLER";


}
