ifndef::imagesdir[:imagesdir: images]

== Building Rico

The build of Rico is based on Gradle.
The Gradle plugins we use for the build currently rely on Gradle version `6.4-rc-1` or higher.
Since the gradle wrapper is used, you do not need to install Gradle on your system.
Because of a bug in the `javadoc` executable of early versions of Java 11 you need Java version `11.0.6` as a minimum version to build rico.
By using older Java 11 releases the build step of the JavaDoc creation will fail.
For executing the integration tests of Rico `docker-compose` (and `docker`) is needed.

A complete build can be started by

....
./gradlew build
....

This will build all modules, create the documentation and will execute the integration tests.

=== Travis setup

Rico is automatically build by https://travis-ci.org[Travis].
The configuration for Travis can be found in the `.travis.yml` YAML file in the root of the repository.
A new travis build will be triggert by each commit to a pull request or the master branch.
All builds can be found https://travis-ci.org/github/rico-projects/rico[here].

