ifndef::imagesdir[:imagesdir: ../images]

== Project structure

Rico is structured in several modules. All these modules are defined as gradle subprojects, 
which will create a jar per module. Next to this each module is defined
as a Java module.

[NOTE]
====
Rico contains in the incubation folder several modules that are in incubation state.
Furthermore Rico contains several modules only needed for internal unit and integration tests
(see folder integration-tests). All these modules may not follow all the rules and
structure defined here.
====

=== Gradle build

In the root folder of the project you can find the `build.gradle` file that defines
the build for the rico project and all subprojects. Instead of externalizing build
tasks in the subprojects we decided to define the build steps for different subprojects
types (java module or documentation) in this central file.

==== Gradle subprojects

All gradle subprojects are defined in the `settings.gradle` located in the root folder of the project.

Each subproject provides its own gradle file, which must have the
same name as the gradle module (based on the entry in `settings.gradle`).
The gradle file for the `rico-client` subproject must be named `rico-client.gradle`.
Each of these gradle files defines the dependencies of the subproject. 
Normally they do not contain any additional information next to the dependencies,
since the general build is defined in the global `build.gradle` file found in the root folder.

Gradle subprojects in Rico won't be released by default. To add a module to releases of Rico
the `publishJars` gradle property must be set to `true`. This is done in the
`gradle.properties` file that is located in all modules that will be included in
a release. The concrete effect of the `publishJars` property can be found in the `build.gradle`
file in the project root folder.

=== Package structure

Each subproject has its sources split into internal and public packages.
This split is additionally defined in the Java module config and hides all private APIs.
While the public API defines its own base package, the packages containing the internal API start with `dev.rico.internal`.
This is done to be compatible with the Java module system.
You can then find a structure like the following one in each module:

....
dev.rico.internal.MODULE_BASE_PACKAGE <- private API

dev.rico.MODULE_BASE_PACKAGE <- public API
....

=== Java Module definition

Each subproject must be defined as a Java Module and must contain
a `module-info.java` file in the `scr/main/java` folder. 

=== Project Graph

Since one main goal of Rico is to provide client side APIs and features
next to the server side modules a lot of modules of rico are targeted for
the client or the server. In general all modules and its dependencies follow
a common pattern that can be found in the base modules as shown in the following
diagram:

image:base-gradle-modules.svg[]
